about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

foodgram/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.conf.urls import handler404, handler500


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),

]

handler404 = 'recipes.views.page_not_found' # noqa
handler500 = 'recipes.views.server_error' # noqa

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

templates/includes/favorite_item.html
{% load user_filters %}
<div class="card" data-id="{{ favorite.recipe.id }}">
    <a href="{% url 'recipe' favorite.recipe.slug %}" class="link" target="_blank">
    <img src="{{ favorite.recipe.image.url }}" alt="{{ favorite.recipe.slug }}" class="card__image"></a>
    <div class="card__body">
        <a class="card__title link" href="{% url 'recipe' favorite.recipe.slug %}" target="_blank">{{ favorite.recipe.recipe_name }}</a>
        <ul class="card__items">
            {% for tag in favorite.recipe.tags.all %}
            {% if tag.slug == 'breakfast'%}
                <li class="card__item"><span class="badge badge_style_orange">{{ tag.title }}</span></li>
            {% elif tag.slug == 'lunch'%}
                <li class="card__item"><span class="badge badge_style_green">{{ tag.title }}</span></li>
            {% else %}
                <li class="card__item"><span class="badge badge_style_purple">{{ tag.title }}</span></li>
            {% endif %}
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ favorite.recipe.time }} мин.</p>
            <p class="card__text"><span class="icon-user"></span> 
                <a href="{% url 'profile' favorite.recipe.author.username %}" style="color: black">
                    {% if favorite.recipe.author.first_name != '' %}
                        {{ favorite.recipe.author.get_full_name }}
                    {% else %}
                        {{ favorite.recipe.author.username }}
                    {% endif %}
                </a>
            </p>
        </div>
    </div>
    <div class="card__footer">
        {% if favorite|to_str in recipe_name_list %}
        <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен</button>
        {% else %}
        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
        {% endif %}
        <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
    </div>
</div>

templates/includes/follow_item.html
{% load mathfilters %}
<div class="card-user" data-author="{{ follow.author.id }}">
    <div class="card-user__header">
        <h2 class="card-user__title">
        {% if follow.author.first_name != '' %}
            {{ follow.author.get_full_name }}
        {% else %}
            {{ follow.author.username }}
        {% endif %}
        </h2>
    </div>
    <div class="card-user__body">
        <ul class="card-user__items">
            {% for recipe in follow.author.recipes_user.all|slice:':3' %}
            <li class="card-user__item">
                <div class="recipe">
                    <img src="{{ recipe.image.url }}" alt="{{ recipe.slug }}" class="recipe__image">
                    <h3 class="recipe__title">{{ recipe.recipe_name }}</h3>
                    <p class="recipe__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
                </div>
            </li>
            {% if forloop.last %}
            {% with count=forloop.counter %}
            <li class="card-user__item">
                <a href="{% url 'profile' follow.author.username %}" class="card-user__link link">Еще {{ follow.author.recipes_user.count|sub:count }} рецептов...</a>
            </li>
            {% endwith %}
            {% endif %}
            {% endfor %}
        </ul>
    </div>
    <div class="card-user__footer">
        <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
    </div>
</div>

templates/includes/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'index' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about:author' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'about:tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

templates/includes/menu.html
{% load user_filters %}
{% if user.is_authenticated %}
    <ul class="nav__items list">
        {% url 'index' as index %}
        <li class="nav__item {% if index|active_url:request %}nav__item_active{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
        {% url 'subscriptions_view' as subscriptions %}
        <li class="nav__item {% if subscriptions|active_url:request %}nav__item_active{% endif %}"><a href="{% url 'subscriptions_view' %}" class="nav__link link">Мои подписки</a></li>
        {% url 'new_recipe' as new_recipe %}
        <li class="nav__item {% if new_recipe|active_url:request %}nav__item_active{% endif %}"><a href="{% url 'new_recipe' %}" class="nav__link link">Создать рецепт</a></li>
        {% url 'favorites_view' as favorites %}
        <li class="nav__item {% if favorites|active_url:request %}nav__item_active{% endif %}"><a href="{% url 'favorites_view' %}" class="nav__link link">Избранное</a></li>
        {% url 'purchases_view' as purchases %}
        <li class="nav__item {% if purchases|active_url:request %}nav__item_active{% endif %}"><a href="{% url 'purchases_view' %}" class="nav__link link">Список покупок</a> <span class="badge badge_style_blue nav__badge" id="counter">{% if count_purchase > 0 %}{{ count_purchase }}{% endif %}</span></li>
    </ul>
{% else %}
    <ul class="nav__items list">
        <li class="nav__item {% if index %}nav__item_active{% endif %}"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
    </ul>
{% endif %}

templates/includes/nav.html
<nav class="nav">
    <div class="nav__container container">
        {% include "includes/menu.html" with active_page=True %}
        {% if user.is_authenticated %}
        <ul class="nav__items list">
            <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
            <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
        </ul>
        {% else %}
        <ul class="nav__items list">
            <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
            <li class="nav__item"><a href="{% url 'signup' %}" class="button button_style_blue">Создать аккаунт</a></li>
        </ul>
        {% endif %}
    </div>

</nav>

templates/includes/paginator.html
<nav class="pagination" aria-label="Search results pages">
    <ul class="pagination__container">
        {% if items.has_previous %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.previous_page_number }}"><span class="icon-left"></span></a></li>
        {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="#" tabindex="-1" aria-disabled="true"><span class="icon-left"></span></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
                {% if items.number == i %}
                <li class="pagination__item pagination__item_active"><span class="pagination__link link">{{ i }} <span class="sr-only"></span></span></li>
                {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
        {% endfor %}
        {% if items.has_next %}
                <li class="pagination__item"><a class="pagination__link link" href="?page={{ items.next_page_number }}"><span class="icon-right"></span></a></li>
        {% else %}
                <li class="pagination__item"><a class="pagination__link link" href="#" tabindex="-1" aria-disabled="true"><span class="icon-right"></span></a></li>
        {% endif %}
    </ul>
</nav>

templates/includes/purchase_item.html
<li class="shopping-list__item" data-id="{{ purchase.id }}">
    <div class="recipe recipe_reverse">
        <img src="{{ purchase.recipe.image.url }}" alt="{{ purchase.recipe.slug }}" class="recipe__image recipe__image_big">
        <h3 class="recipe__title">{{ purchase.recipe.recipe_name }}</h3>
        <p class="recipe__text"><span class="icon-time"></span> {{ purchase.recipe.time }} мин.
    </div>
    <a href="{% url 'delete_purchases' purchase.id %}"  class="shopping-list__button link">Удалить</a>
</li>

templates/includes/recipe_item.html
{% load user_filters %}
<div class="card" data-id="{{ recipe.id }}">
    <a href="{% url 'recipe' recipe.slug %}" class="link" target="_blank">
    <img src="{{ recipe.image.url }}" alt="{{ recipe.slug }}" class="card__image"></a>
    <div class="card__body">
        <a class="card__title link" href="{% url 'recipe' recipe.slug %}" target="_blank">{{ recipe.recipe_name }}</a>
        <ul class="card__items">
            {% for tag in recipe.tags.all %}
            {% if tag.slug == 'breakfast'%}
                <li class="card__item"><span class="badge badge_style_orange">{{ tag.title }}</span></li>
            {% elif tag.slug == 'lunch'%}
                <li class="card__item"><span class="badge badge_style_green">{{ tag.title }}</span></li>
            {% else %}
                <li class="card__item"><span class="badge badge_style_purple">{{ tag.title }}</span></li>
            {% endif %}
            {% endfor %}
        </ul>
        <div class="card__items card__items_column">
            <p class="card__text"><span class="icon-time"></span> {{ recipe.time }} мин.</p>
            <p class="card__text"><span class="icon-user"></span> 
                <a href="{% url 'profile' recipe.author.username %}" style="color: black">
                    {% if recipe.author.first_name != '' %}
                        {{ recipe.author.get_full_name }}
                    {% else %}
                        {{ recipe.author.username }}
                    {% endif %}
                </a>
            </p>
        </div>
    </div>
    <div class="card__footer">
        {% if user.is_authenticated %}
        {% if recipe|to_str in purchase_recipes %}
        <button class="button button_style_light-blue-outline" name="purchases"><span class="icon-check button__icon"></span> Рецепт добавлен</button>
        {% else %}
        <button class="button button_style_light-blue" name="purchases" data-out><span class="icon-plus button__icon"></span>Добавить в покупки</button>
        {% endif %}
        {% if recipe|to_str in favorite_recipes %}
        <button class="button button_style_none" name="favorites"><span class="icon-favorite icon-favorite_active"></span></button>
        {% else %}
        <button class="button button_style_none" name="favorites" data-out><span class="icon-favorite"></span></button>
        {% endif %}
        {% endif %}
    </div>
</div>

templates/includes/tag_filter.html
{% load user_filters %}
<ul class="tags">
    <li class="tags__item">
        <a  id="breakfast"
            class="tags__checkbox tags__checkbox_style_orange
                {% if 'breakfast' in tags %}tags__checkbox_active{% endif %}"
            href="{% if 'breakfast' in tags %}{% url request.resolver_match.url_name %}?page={{page_number}}{{ tags|cut_tag:'breakfast' }}
                {% else %}{% url request.resolver_match.url_name %}?page={{page_number}}{{ tags|add_tag:'breakfast' }}{% endif %}">
        </a>
        <label for="lunch" class="tags__label">Завтрак</label>
    </li>
    <li class="tags__item">
        <a  id="lunch"
            class="tags__checkbox tags__checkbox_style_green
                {% if 'lunch' in tags %}tags__checkbox_active{% endif %}"
            href="{% if 'lunch' in tags %}{% url request.resolver_match.url_name %}?page={{page_number}}{{ tags|cut_tag:'lunch' }}
                {% else %}{% url request.resolver_match.url_name %}?page={{page_number}}{{ tags|add_tag:'lunch' }}{% endif %}">
        </a>
        <label for="lunch" class="tags__label">Обед</label>
    </li>
    <li class="tags__item">
        <a  id="dinner"
            class="tags__checkbox tags__checkbox_style_purple
                {% if 'dinner' in tags %}tags__checkbox_active{% endif %}" 
            href="{% if 'dinner' in tags %}{% url request.resolver_match.url_name %}?page={{page_number}}{{ tags|cut_tag:'dinner' }}
                {% else %}{% url request.resolver_match.url_name %}?page={{page_number}}{{ tags|add_tag:'dinner' }}{% endif %}">
        </a>
        <span for="dinner" class="tags__label">Ужин</span>
    </li>

templates/includes/tag_filter_profile.html
{% load user_filters %}
<ul class="tags">
    <li class="tags__item">
        <a  id="breakfast"
            class="tags__checkbox tags__checkbox_style_orange
                {% if 'breakfast' in tags %}tags__checkbox_active{% endif %}"
            href="{% if 'breakfast' in tags %}{% url 'profile' author.username %}?page={{page_number}}{{ tags|cut_tag:'breakfast' }}
                {% else %}{% url 'profile' author.username %}?page={{page_number}}{{ tags|add_tag:'breakfast' }}{% endif %}">
        </a>
        <label for="lunch" class="tags__label">Завтрак</label>
    </li>
    <li class="tags__item">
        <a  id="lunch"
            class="tags__checkbox tags__checkbox_style_green
                {% if 'lunch' in tags %}tags__checkbox_active{% endif %}"
            href="{% if 'lunch' in tags %}{% url 'profile' author.username %}?page={{page_number}}{{ tags|cut_tag:'lunch' }}
                {% else %}{% url 'profile' author.username %}?page={{page_number}}{{ tags|add_tag:'lunch' }}{% endif %}">
        </a>
        <label for="lunch" class="tags__label">Обед</label>
    </li>
    <li class="tags__item">
        <a  id="dinner"
            class="tags__checkbox tags__checkbox_style_purple
                {% if 'dinner' in tags %}tags__checkbox_active{% endif %}" 
            href="{% if 'dinner' in tags %}{% url 'profile' author.username %}?page={{page_number}}{{ tags|cut_tag:'dinner' }}
                {% else %}{% url 'profile' author.username %}?page={{page_number}}{{ tags|add_tag:'dinner' }}{% endif %}">
        </a>
        <span for="dinner" class="tags__label">Ужин</span>
    </li>